spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aa_recipeapp_dev
    username: aa_recipeapp_dev_user
    password: dev
  sql:
    init:
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true

# uncomment and run the project for initial database scripts to be generated, then you can run them
# inside created database(first create database with configure-mysql-{environment_type}.sql)
#    properties:
#      hibernate:
#        hbm2ddl:
#          delimiter: ";"
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: src/main/scripts/spring_database_create.sql

