spring:
  datasource:
    url: jdbc:mysql://localhost:3307/aa_recipeapp_prod
    username: aa_recipeapp_prod_user
    password: prod
  sql:
    init:
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false